"""Hybrid retrieval package.

Public interface: ``HybridRetriever`` wires together dense vector search,
BM25 sparse search, RRF fusion, and CrossEncoder reranking into a single
``retrieve(query)`` call.
"""

from __future__ import annotations

from src.config import CONFIG
from src.retrieval.bm25_store import BM25Store
from src.retrieval.hybrid import reciprocal_rank_fusion
from src.retrieval.reranker import Reranker
from src.retrieval.vector_store import VectorStore


class HybridRetriever:
    """Full hybrid retrieval pipeline.

    Combines BM25 sparse retrieval and dense vector retrieval via Reciprocal
    Rank Fusion, then applies CrossEncoder reranking to produce a final
    ranked list of the most relevant chunks.

    Attributes:
        vector_store: The ``VectorStore`` instance for dense retrieval.
        bm25_store: The ``BM25Store`` instance for sparse retrieval.
    """

    def __init__(self) -> None:
        self.vector_store = VectorStore()
        self.bm25_store = BM25Store()
        self._reranker = Reranker()
        # Attempt to load BM25 index from disk; log if unavailable
        loaded = self.bm25_store.load()
        if not loaded:
            print(
                "Warning: BM25 index not found on disk. "
                "Run the ingestion pipeline first."
            )

    def retrieve(self, query: str, hyde_query: str | None = None) -> list[dict]:
        """Full retrieval pipeline for a single query.

        Steps:
            1. Dense vector search using ``hyde_query`` if provided, otherwise
               the original ``query``.  HyDE improves dense recall by using
               vocabulary closer to document chunks; BM25 always uses the
               original query because the hypothetical text adds noise to
               keyword matching.
            2. BM25 keyword search on the original ``query``, returning
               ``CONFIG.retrieval_k_candidate`` candidates (skipped with a
               warning if the index is not ready).
            3. RRF fusion of both result lists.
            4. CrossEncoder reranking on the original ``query``, returning
               ``CONFIG.retrieval_k_final`` chunks.

        Args:
            query: The user's natural-language query string. Used for BM25,
                RRF, and CrossEncoder reranking.
            hyde_query: Optional hypothetical passage generated by
                ``HyDEExpander``. When provided, used in place of ``query``
                for dense vector retrieval only.

        Returns:
            List of up to ``CONFIG.retrieval_k_final`` chunk dicts, each
            containing ``"content"``, ``"metadata"``, ``"rrf_score"``, and
            ``"rerank_score"`` fields.
        """
        dense_query = hyde_query if hyde_query else query

        dense_results = self.vector_store.search(
            dense_query, k=CONFIG.retrieval_k_candidate
        )

        if self.bm25_store.is_ready:
            sparse_results = self.bm25_store.search(
                query, k=CONFIG.retrieval_k_candidate
            )
        else:
            print("Warning: BM25 index not ready; falling back to dense-only retrieval.")
            sparse_results = []

        fused = reciprocal_rank_fusion(dense_results, sparse_results)

        return self._reranker.rerank(query, fused, k=CONFIG.retrieval_k_final)
